### ISSUE TITLE
Charcreator Camera problem.

### ISSUE THREAD

**Issue by PolishDywan** [GuilhermeTrevizani/trevizani-roleplay#3]
problem with camera in Character Creator... How to fix that? 

![discordpotwierdzenie](https://github.com/GuilhermeTrevizani/roleplay-server/assets/65501143/cea33854-cdc7-439e-8156-9c6bdf1db686)

**Comment by GuilhermeTrevizani** [comment]
I think this problem started with a new update that uses the Frozen Player property on the server side. I'm updating the server to alt:V 15 in the develop branch and I'm going to do some tests to try to find out the real reason.

**Comment by GuilhermeTrevizani** [comment]
Please try with new commited changes.

**Comment by PolishDywan** [comment]
Today I tried to play with this gamemode again, the problem still exists. :)

**Comment by GuilhermeTrevizani** [comment]
I'll try something soon.

**Comment by GuilhermeTrevizani** [comment]
Fixed.

**Comment by PolishDywan** [comment]
Treviza, you scare me sometimes. I was just downloading the repository again XD! Thank you! :)
