### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kadet2850** [GuilhermeTrevizani/trevizani-roleplay#7]
Hello, could you please advise on how to correctly implement authentication? I've managed to set everything up without any issues, but I can't figure out what's wrong with the authentication. The 'Login with Discord' button is not clickable!
![image](https://github.com/GuilhermeTrevizani/trevizani-roleplay/assets/145415270/c2c9b6c1-7723-4305-beb1-414946e328f0)
![image](https://github.com/GuilhermeTrevizani/trevizani-roleplay/assets/145415270/2e8d97aa-1865-40a4-8eca-df8afca3b6ce)
![image](https://github.com/GuilhermeTrevizani/trevizani-roleplay/assets/145415270/97f8c1f6-f41b-4eea-8d6b-ec0b69d24fed)

**Comment by GuilhermeTrevizani** [comment]
https://github.com/GuilhermeTrevizani/trevizani-roleplay/blob/71a1b59506441f8b91efbe3addfc213c0f9aeba8/ALTVSERVER/resources/client/helpers/constants.js#L13
Here you can set your the Discord App Id. 

Press F8 to show the error on alt:V console and send your screenshot here.
